In [1]:
from sklearn.datasets import make_blobs
import numpy as np
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt

In [2]:
## GENERATIONS DES INTERVALES D'HEURES

In [3]:
H1= np.linspace(4.5,7.0,50)
H1

array([4.5       , 4.55102041, 4.60204082, 4.65306122, 4.70408163,
       4.75510204, 4.80612245, 4.85714286, 4.90816327, 4.95918367,
       5.01020408, 5.06122449, 5.1122449 , 5.16326531, 5.21428571,
       5.26530612, 5.31632653, 5.36734694, 5.41836735, 5.46938776,
       5.52040816, 5.57142857, 5.62244898, 5.67346939, 5.7244898 ,
       5.7755102 , 5.82653061, 5.87755102, 5.92857143, 5.97959184,
       6.03061224, 6.08163265, 6.13265306, 6.18367347, 6.23469388,
       6.28571429, 6.33673469, 6.3877551 , 6.43877551, 6.48979592,
       6.54081633, 6.59183673, 6.64285714, 6.69387755, 6.74489796,
       6.79591837, 6.84693878, 6.89795918, 6.94897959, 7.        ])

In [4]:
H2= np.linspace(7.0,10.3,50)
H2

array([ 7.        ,  7.06734694,  7.13469388,  7.20204082,  7.26938776,
        7.33673469,  7.40408163,  7.47142857,  7.53877551,  7.60612245,
        7.67346939,  7.74081633,  7.80816327,  7.8755102 ,  7.94285714,
        8.01020408,  8.07755102,  8.14489796,  8.2122449 ,  8.27959184,
        8.34693878,  8.41428571,  8.48163265,  8.54897959,  8.61632653,
        8.68367347,  8.75102041,  8.81836735,  8.88571429,  8.95306122,
        9.02040816,  9.0877551 ,  9.15510204,  9.22244898,  9.28979592,
        9.35714286,  9.4244898 ,  9.49183673,  9.55918367,  9.62653061,
        9.69387755,  9.76122449,  9.82857143,  9.89591837,  9.96326531,
       10.03061224, 10.09795918, 10.16530612, 10.23265306, 10.3       ])

In [5]:
H3= np.linspace(10.3,16.0,50)
H3

array([10.3       , 10.41632653, 10.53265306, 10.64897959, 10.76530612,
       10.88163265, 10.99795918, 11.11428571, 11.23061224, 11.34693878,
       11.46326531, 11.57959184, 11.69591837, 11.8122449 , 11.92857143,
       12.04489796, 12.16122449, 12.27755102, 12.39387755, 12.51020408,
       12.62653061, 12.74285714, 12.85918367, 12.9755102 , 13.09183673,
       13.20816327, 13.3244898 , 13.44081633, 13.55714286, 13.67346939,
       13.78979592, 13.90612245, 14.02244898, 14.13877551, 14.25510204,
       14.37142857, 14.4877551 , 14.60408163, 14.72040816, 14.83673469,
       14.95306122, 15.06938776, 15.18571429, 15.30204082, 15.41836735,
       15.53469388, 15.65102041, 15.76734694, 15.88367347, 16.        ])

In [6]:
H4= np.linspace(16.0,19.0,50)
H4

array([16.        , 16.06122449, 16.12244898, 16.18367347, 16.24489796,
       16.30612245, 16.36734694, 16.42857143, 16.48979592, 16.55102041,
       16.6122449 , 16.67346939, 16.73469388, 16.79591837, 16.85714286,
       16.91836735, 16.97959184, 17.04081633, 17.10204082, 17.16326531,
       17.2244898 , 17.28571429, 17.34693878, 17.40816327, 17.46938776,
       17.53061224, 17.59183673, 17.65306122, 17.71428571, 17.7755102 ,
       17.83673469, 17.89795918, 17.95918367, 18.02040816, 18.08163265,
       18.14285714, 18.20408163, 18.26530612, 18.32653061, 18.3877551 ,
       18.44897959, 18.51020408, 18.57142857, 18.63265306, 18.69387755,
       18.75510204, 18.81632653, 18.87755102, 18.93877551, 19.        ])

In [7]:
H5= np.linspace(19.0,22.3,50)
H5

array([19.        , 19.06734694, 19.13469388, 19.20204082, 19.26938776,
       19.33673469, 19.40408163, 19.47142857, 19.53877551, 19.60612245,
       19.67346939, 19.74081633, 19.80816327, 19.8755102 , 19.94285714,
       20.01020408, 20.07755102, 20.14489796, 20.2122449 , 20.27959184,
       20.34693878, 20.41428571, 20.48163265, 20.54897959, 20.61632653,
       20.68367347, 20.75102041, 20.81836735, 20.88571429, 20.95306122,
       21.02040816, 21.0877551 , 21.15510204, 21.22244898, 21.28979592,
       21.35714286, 21.4244898 , 21.49183673, 21.55918367, 21.62653061,
       21.69387755, 21.76122449, 21.82857143, 21.89591837, 21.96326531,
       22.03061224, 22.09795918, 22.16530612, 22.23265306, 22.3       ])

In [8]:
## GENERATION DES INTERVALES DE DISTANCES

In [9]:
D1=np.linspace(10,20,50)
D1

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [10]:
D2=np.linspace(20,40,50)
D2

array([20.        , 20.40816327, 20.81632653, 21.2244898 , 21.63265306,
       22.04081633, 22.44897959, 22.85714286, 23.26530612, 23.67346939,
       24.08163265, 24.48979592, 24.89795918, 25.30612245, 25.71428571,
       26.12244898, 26.53061224, 26.93877551, 27.34693878, 27.75510204,
       28.16326531, 28.57142857, 28.97959184, 29.3877551 , 29.79591837,
       30.20408163, 30.6122449 , 31.02040816, 31.42857143, 31.83673469,
       32.24489796, 32.65306122, 33.06122449, 33.46938776, 33.87755102,
       34.28571429, 34.69387755, 35.10204082, 35.51020408, 35.91836735,
       36.32653061, 36.73469388, 37.14285714, 37.55102041, 37.95918367,
       38.36734694, 38.7755102 , 39.18367347, 39.59183673, 40.        ])

In [11]:
D3=np.linspace(40,60,50)
D3

array([40.        , 40.40816327, 40.81632653, 41.2244898 , 41.63265306,
       42.04081633, 42.44897959, 42.85714286, 43.26530612, 43.67346939,
       44.08163265, 44.48979592, 44.89795918, 45.30612245, 45.71428571,
       46.12244898, 46.53061224, 46.93877551, 47.34693878, 47.75510204,
       48.16326531, 48.57142857, 48.97959184, 49.3877551 , 49.79591837,
       50.20408163, 50.6122449 , 51.02040816, 51.42857143, 51.83673469,
       52.24489796, 52.65306122, 53.06122449, 53.46938776, 53.87755102,
       54.28571429, 54.69387755, 55.10204082, 55.51020408, 55.91836735,
       56.32653061, 56.73469388, 57.14285714, 57.55102041, 57.95918367,
       58.36734694, 58.7755102 , 59.18367347, 59.59183673, 60.        ])

In [12]:
D4=np.linspace(60,80,50)
D4

array([60.        , 60.40816327, 60.81632653, 61.2244898 , 61.63265306,
       62.04081633, 62.44897959, 62.85714286, 63.26530612, 63.67346939,
       64.08163265, 64.48979592, 64.89795918, 65.30612245, 65.71428571,
       66.12244898, 66.53061224, 66.93877551, 67.34693878, 67.75510204,
       68.16326531, 68.57142857, 68.97959184, 69.3877551 , 69.79591837,
       70.20408163, 70.6122449 , 71.02040816, 71.42857143, 71.83673469,
       72.24489796, 72.65306122, 73.06122449, 73.46938776, 73.87755102,
       74.28571429, 74.69387755, 75.10204082, 75.51020408, 75.91836735,
       76.32653061, 76.73469388, 77.14285714, 77.55102041, 77.95918367,
       78.36734694, 78.7755102 , 79.18367347, 79.59183673, 80.        ])

In [13]:
D5=np.linspace(80,100,50)
D5

array([ 80.        ,  80.40816327,  80.81632653,  81.2244898 ,
        81.63265306,  82.04081633,  82.44897959,  82.85714286,
        83.26530612,  83.67346939,  84.08163265,  84.48979592,
        84.89795918,  85.30612245,  85.71428571,  86.12244898,
        86.53061224,  86.93877551,  87.34693878,  87.75510204,
        88.16326531,  88.57142857,  88.97959184,  89.3877551 ,
        89.79591837,  90.20408163,  90.6122449 ,  91.02040816,
        91.42857143,  91.83673469,  92.24489796,  92.65306122,
        93.06122449,  93.46938776,  93.87755102,  94.28571429,
        94.69387755,  95.10204082,  95.51020408,  95.91836735,
        96.32653061,  96.73469388,  97.14285714,  97.55102041,
        97.95918367,  98.36734694,  98.7755102 ,  99.18367347,
        99.59183673, 100.        ])

In [14]:
## GENERATION DES INTERVALES DE VITESSES

In [15]:
V1=np.linspace(1,5,50)
V1

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [16]:
V2=np.linspace(5,10,50)
V2

array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

In [17]:
V3=np.linspace(10,15,50)
V3

array([10.        , 10.10204082, 10.20408163, 10.30612245, 10.40816327,
       10.51020408, 10.6122449 , 10.71428571, 10.81632653, 10.91836735,
       11.02040816, 11.12244898, 11.2244898 , 11.32653061, 11.42857143,
       11.53061224, 11.63265306, 11.73469388, 11.83673469, 11.93877551,
       12.04081633, 12.14285714, 12.24489796, 12.34693878, 12.44897959,
       12.55102041, 12.65306122, 12.75510204, 12.85714286, 12.95918367,
       13.06122449, 13.16326531, 13.26530612, 13.36734694, 13.46938776,
       13.57142857, 13.67346939, 13.7755102 , 13.87755102, 13.97959184,
       14.08163265, 14.18367347, 14.28571429, 14.3877551 , 14.48979592,
       14.59183673, 14.69387755, 14.79591837, 14.89795918, 15.        ])

In [18]:
V4=np.linspace(15,20,50)
V4

array([15.        , 15.10204082, 15.20408163, 15.30612245, 15.40816327,
       15.51020408, 15.6122449 , 15.71428571, 15.81632653, 15.91836735,
       16.02040816, 16.12244898, 16.2244898 , 16.32653061, 16.42857143,
       16.53061224, 16.63265306, 16.73469388, 16.83673469, 16.93877551,
       17.04081633, 17.14285714, 17.24489796, 17.34693878, 17.44897959,
       17.55102041, 17.65306122, 17.75510204, 17.85714286, 17.95918367,
       18.06122449, 18.16326531, 18.26530612, 18.36734694, 18.46938776,
       18.57142857, 18.67346939, 18.7755102 , 18.87755102, 18.97959184,
       19.08163265, 19.18367347, 19.28571429, 19.3877551 , 19.48979592,
       19.59183673, 19.69387755, 19.79591837, 19.89795918, 20.        ])

In [19]:
## GENERATION DES DICTIONNAIRES

In [20]:
H={
    'H1':H1.reshape(-1,1),
    'H2':H2.reshape(-1,1),
    'H3':H3.reshape(-1,1),
    'H4':H4.reshape(-1,1),
    'H5':H5.reshape(-1,1),   
}

V={
    'V1':V1.reshape(-1,1),
    'V2':V2.reshape(-1,1),
    'V3':V3.reshape(-1,1),
    'V4':V4.reshape(-1,1), 
}

D={
    'D1':D1.reshape(-1,1),
    'D2':D2.reshape(-1,1),
    'D3':D3.reshape(-1,1),
    'D4':D4.reshape(-1,1),
    'D5':D5.reshape(-1,1),
}

In [21]:
def create_H_V_D_T(V,H,D):
    len_V=len(V)
    len_H=len(H)
    len_D=len(D)
    HVD={}

    for i in range(len_H):
        for j in range(len_V):
            for k in range(len_D):
                HVD['H'+str(i+1)+'_V'+str(j+1)+'_D'+str(k+1)]=[H['H'+str(i+1)],V['V'+str(j+1)],D['D'+str(k+1)]]

    HVDT={}
    L_VH=['H1','H2','H3','H4','H5']
    DeltaTime=[[0,0],[1.5,2],[0,0.5],[2,3],[0,0]]
    
    for j in range(len(L_VH)):
        for i in HVD:
            if i[:2]==L_VH[j]:
                
                D_HVD= [HVD[i][2][0],HVD[i][2][-1]]
                D_HVD
                V_HVD= [HVD[i][1][0],HVD[i][1][-1]]
                V_HVD
                T_HVD= [(D_HVD[0]/V_HVD[0])+DeltaTime[j][0],(D_HVD[1]/V_HVD[1])+DeltaTime[j][1]]
                T_HVD
                T=np.linspace(T_HVD[0],T_HVD[1],50)
                
                HVD[i].append(T)
                HVDT[i+'_T']= HVD[i]

                
    return HVDT

In [22]:
HVDT=create_H_V_D_T(V,H,D)

In [23]:
HVDT

{'H1_V1_D1_T': [array([[4.5       ],
         [4.55102041],
         [4.60204082],
         [4.65306122],
         [4.70408163],
         [4.75510204],
         [4.80612245],
         [4.85714286],
         [4.90816327],
         [4.95918367],
         [5.01020408],
         [5.06122449],
         [5.1122449 ],
         [5.16326531],
         [5.21428571],
         [5.26530612],
         [5.31632653],
         [5.36734694],
         [5.41836735],
         [5.46938776],
         [5.52040816],
         [5.57142857],
         [5.62244898],
         [5.67346939],
         [5.7244898 ],
         [5.7755102 ],
         [5.82653061],
         [5.87755102],
         [5.92857143],
         [5.97959184],
         [6.03061224],
         [6.08163265],
         [6.13265306],
         [6.18367347],
         [6.23469388],
         [6.28571429],
         [6.33673469],
         [6.3877551 ],
         [6.43877551],
         [6.48979592],
         [6.54081633],
         [6.59183673],
         [6.64285714

In [24]:
def create_pandas_dataset(V,H,D):

    import pandas as pd
    HVDT= create_H_V_D_T(V,H,D)
    
    df= pd.DataFrame({
        'Heure_Depart':[],
        'Vitesse_Moyenne':[],
        'Distance':[],
        'Temps_Estimé':[]
    })
    
    for i in HVDT:
        
        H=[]
        V=[]
        D=[]
        T=[]

        for j in HVDT[i][0]:
            H.append(float(j))
        for j in HVDT[i][1]:
            V.append(float(j))
        for j in HVDT[i][2]:
            D.append(float(j))
        for j in HVDT[i][3]:
            T.append(float(j))
            
        datasets = pd.DataFrame({'Heure_Depart':H})
        datasets['Vitesse_Moyenne'] = pd.DataFrame({'Vitesse_Moyenne':V})
        datasets['Distance'] = pd.DataFrame({'Distance':D})
        datasets['Temps_Estimé'] = pd.DataFrame({'Temps_Estimé':T})

        df= pd.concat([df, datasets], ignore_index=True)

    df.to_csv('Transport_Set.csv', index=False)

    return df

In [25]:
df=create_pandas_dataset(V,H,D)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_8224\800369299.py:21: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  H.append(float(j))
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_8224\800369299.py:23: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  V.append(float(j))
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_8224\800369299.py:25: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  D.append(float(j))
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_8224\800369299.py:27: Deprec

In [26]:
df

,Heure_Depart,Vitesse_Moyenne,Distance,Temps_Estimé
0,4.500000,1.000000,10.000000,10.000000
1,4.551020,1.081633,10.204082,9.877551
2,4.602041,1.163265,10.408163,9.755102
3,4.653061,1.244898,10.612245,9.632653
4,4.704082,1.326531,10.816327,9.510204
...,...,...,...,...
4995,22.030612,19.591837,98.367347,5.027211
4996,22.097959,19.693878,98.775510,5.020408
4997,22.165306,19.795918,99.183673,5.013605
4998,22.232653,19.897959,99.591837,5.006803


In [27]:
def transport_LinearRegression_modal(df_file):
    import pandas as pd
    from sklearn.model_selection import train_test_split
    from sklearn.linear_model import LinearRegression

    df= pd.read_csv(df_file)
    X=df[['Heure_Depart','Vitesse_Moyenne','Distance']].values
    y=df[['Temps_Estimé']].values


    X_train, X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=40)
    
    modal= LinearRegression()
    modal.fit(X_train,y_train)

    prediction_train=modal.predict(X_train)
    prediction_test=modal.predict(X_test)
    
    score_train=modal.score(X_train,y_train)
    score_test=modal.score(X_test,y_test)
    
    print("Score de l'entrainement : ", score_train)
    print("Score du test : ", score_test)

    dict_train={
        'X':X_train,
        'y':y_train,
        'prediction':prediction_train,
        'score':score_train
    }
    
    dict_test={
        'X':X_test,
        'y':y_test,
        'prediction':prediction_test,
        'score':score_test
    }

    
    return(modal,dict_train,dict_test)

In [28]:
modal_LinearRegression,dict_train_LinearRegression,dict_test_LinearRegression=transport_LinearRegression_modal('Transport_Set.csv')

Score de l'entrainement :  0.5528174740882905
Score du test :  0.5225748852932044


In [29]:
modal_LinearRegression.predict([[16.5,17.9,8]])

array([[-9.9402413]])

In [30]:
def transport_RandomForestRegressor_modal(df_file):
    import pandas as pd
    from sklearn.model_selection import train_test_split
    from sklearn.ensemble import RandomForestRegressor

    df= pd.read_csv(df_file)
    X=df[['Heure_Depart','Vitesse_Moyenne','Distance']].values
    y=df[['Temps_Estimé']].values


    X_train, X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=40)
    
    modal= RandomForestRegressor(n_estimators=100, random_state=42)
    modal.fit(X_train,y_train)

    prediction_train=modal.predict(X_train)
    prediction_test=modal.predict(X_test)
    
    score_train=modal.score(X_train,y_train)
    score_test=modal.score(X_test,y_test)
    
    print("Score de l'entrainement : ", score_train)
    print("Score du test : ", score_test)

    dict_train={
        'X':X_train,
        'y':y_train,
        'prediction':prediction_train,
        'score':score_train
    }
    
    dict_test={
        'X':X_test,
        'y':y_test,
        'prediction':prediction_test,
        'score':score_test
    }

    
    return(modal,dict_train,dict_test)

In [31]:
modal_RandomForestRegressor,dict_train_RandomForestRegressor,dict_test_RandomForestRegressor=transport_RandomForestRegressor_modal('Transport_Set.csv')

C:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Score de l'entrainement :  0.9997401628792602
Score du test :  0.9985785197056156


In [32]:
modal_RandomForestRegressor.predict([[16.5,17.9,8]])

array([2.62503401])