In [228]:
from sklearn.datasets import make_blobs
import numpy as np
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt

In [103]:
H1= np.linspace(4.5,7.0,50)
H1

array([4.5       , 4.55102041, 4.60204082, 4.65306122, 4.70408163,
       4.75510204, 4.80612245, 4.85714286, 4.90816327, 4.95918367,
       5.01020408, 5.06122449, 5.1122449 , 5.16326531, 5.21428571,
       5.26530612, 5.31632653, 5.36734694, 5.41836735, 5.46938776,
       5.52040816, 5.57142857, 5.62244898, 5.67346939, 5.7244898 ,
       5.7755102 , 5.82653061, 5.87755102, 5.92857143, 5.97959184,
       6.03061224, 6.08163265, 6.13265306, 6.18367347, 6.23469388,
       6.28571429, 6.33673469, 6.3877551 , 6.43877551, 6.48979592,
       6.54081633, 6.59183673, 6.64285714, 6.69387755, 6.74489796,
       6.79591837, 6.84693878, 6.89795918, 6.94897959, 7.        ])

In [104]:
H2= np.linspace(7.0,10.3,50)
H2

array([ 7.        ,  7.06734694,  7.13469388,  7.20204082,  7.26938776,
        7.33673469,  7.40408163,  7.47142857,  7.53877551,  7.60612245,
        7.67346939,  7.74081633,  7.80816327,  7.8755102 ,  7.94285714,
        8.01020408,  8.07755102,  8.14489796,  8.2122449 ,  8.27959184,
        8.34693878,  8.41428571,  8.48163265,  8.54897959,  8.61632653,
        8.68367347,  8.75102041,  8.81836735,  8.88571429,  8.95306122,
        9.02040816,  9.0877551 ,  9.15510204,  9.22244898,  9.28979592,
        9.35714286,  9.4244898 ,  9.49183673,  9.55918367,  9.62653061,
        9.69387755,  9.76122449,  9.82857143,  9.89591837,  9.96326531,
       10.03061224, 10.09795918, 10.16530612, 10.23265306, 10.3       ])

In [105]:
H3= np.linspace(10.3,16.0,50)
H3

array([10.3       , 10.41632653, 10.53265306, 10.64897959, 10.76530612,
       10.88163265, 10.99795918, 11.11428571, 11.23061224, 11.34693878,
       11.46326531, 11.57959184, 11.69591837, 11.8122449 , 11.92857143,
       12.04489796, 12.16122449, 12.27755102, 12.39387755, 12.51020408,
       12.62653061, 12.74285714, 12.85918367, 12.9755102 , 13.09183673,
       13.20816327, 13.3244898 , 13.44081633, 13.55714286, 13.67346939,
       13.78979592, 13.90612245, 14.02244898, 14.13877551, 14.25510204,
       14.37142857, 14.4877551 , 14.60408163, 14.72040816, 14.83673469,
       14.95306122, 15.06938776, 15.18571429, 15.30204082, 15.41836735,
       15.53469388, 15.65102041, 15.76734694, 15.88367347, 16.        ])

In [106]:
H4= np.linspace(16.0,19.0,50)
H4

array([16.        , 16.06122449, 16.12244898, 16.18367347, 16.24489796,
       16.30612245, 16.36734694, 16.42857143, 16.48979592, 16.55102041,
       16.6122449 , 16.67346939, 16.73469388, 16.79591837, 16.85714286,
       16.91836735, 16.97959184, 17.04081633, 17.10204082, 17.16326531,
       17.2244898 , 17.28571429, 17.34693878, 17.40816327, 17.46938776,
       17.53061224, 17.59183673, 17.65306122, 17.71428571, 17.7755102 ,
       17.83673469, 17.89795918, 17.95918367, 18.02040816, 18.08163265,
       18.14285714, 18.20408163, 18.26530612, 18.32653061, 18.3877551 ,
       18.44897959, 18.51020408, 18.57142857, 18.63265306, 18.69387755,
       18.75510204, 18.81632653, 18.87755102, 18.93877551, 19.        ])

In [107]:
H5= np.linspace(19.0,22.3,50)
H5

array([19.        , 19.06734694, 19.13469388, 19.20204082, 19.26938776,
       19.33673469, 19.40408163, 19.47142857, 19.53877551, 19.60612245,
       19.67346939, 19.74081633, 19.80816327, 19.8755102 , 19.94285714,
       20.01020408, 20.07755102, 20.14489796, 20.2122449 , 20.27959184,
       20.34693878, 20.41428571, 20.48163265, 20.54897959, 20.61632653,
       20.68367347, 20.75102041, 20.81836735, 20.88571429, 20.95306122,
       21.02040816, 21.0877551 , 21.15510204, 21.22244898, 21.28979592,
       21.35714286, 21.4244898 , 21.49183673, 21.55918367, 21.62653061,
       21.69387755, 21.76122449, 21.82857143, 21.89591837, 21.96326531,
       22.03061224, 22.09795918, 22.16530612, 22.23265306, 22.3       ])

In [108]:
D1=np.linspace(10,20,50)
D1

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [109]:
D2=np.linspace(20,40,50)
D2

array([20.        , 20.40816327, 20.81632653, 21.2244898 , 21.63265306,
       22.04081633, 22.44897959, 22.85714286, 23.26530612, 23.67346939,
       24.08163265, 24.48979592, 24.89795918, 25.30612245, 25.71428571,
       26.12244898, 26.53061224, 26.93877551, 27.34693878, 27.75510204,
       28.16326531, 28.57142857, 28.97959184, 29.3877551 , 29.79591837,
       30.20408163, 30.6122449 , 31.02040816, 31.42857143, 31.83673469,
       32.24489796, 32.65306122, 33.06122449, 33.46938776, 33.87755102,
       34.28571429, 34.69387755, 35.10204082, 35.51020408, 35.91836735,
       36.32653061, 36.73469388, 37.14285714, 37.55102041, 37.95918367,
       38.36734694, 38.7755102 , 39.18367347, 39.59183673, 40.        ])

In [110]:
D3=np.linspace(40,60,50)
D3

array([40.        , 40.40816327, 40.81632653, 41.2244898 , 41.63265306,
       42.04081633, 42.44897959, 42.85714286, 43.26530612, 43.67346939,
       44.08163265, 44.48979592, 44.89795918, 45.30612245, 45.71428571,
       46.12244898, 46.53061224, 46.93877551, 47.34693878, 47.75510204,
       48.16326531, 48.57142857, 48.97959184, 49.3877551 , 49.79591837,
       50.20408163, 50.6122449 , 51.02040816, 51.42857143, 51.83673469,
       52.24489796, 52.65306122, 53.06122449, 53.46938776, 53.87755102,
       54.28571429, 54.69387755, 55.10204082, 55.51020408, 55.91836735,
       56.32653061, 56.73469388, 57.14285714, 57.55102041, 57.95918367,
       58.36734694, 58.7755102 , 59.18367347, 59.59183673, 60.        ])

In [111]:
D4=np.linspace(60,80,50)
D4

array([60.        , 60.40816327, 60.81632653, 61.2244898 , 61.63265306,
       62.04081633, 62.44897959, 62.85714286, 63.26530612, 63.67346939,
       64.08163265, 64.48979592, 64.89795918, 65.30612245, 65.71428571,
       66.12244898, 66.53061224, 66.93877551, 67.34693878, 67.75510204,
       68.16326531, 68.57142857, 68.97959184, 69.3877551 , 69.79591837,
       70.20408163, 70.6122449 , 71.02040816, 71.42857143, 71.83673469,
       72.24489796, 72.65306122, 73.06122449, 73.46938776, 73.87755102,
       74.28571429, 74.69387755, 75.10204082, 75.51020408, 75.91836735,
       76.32653061, 76.73469388, 77.14285714, 77.55102041, 77.95918367,
       78.36734694, 78.7755102 , 79.18367347, 79.59183673, 80.        ])

In [387]:
D5=np.linspace(80,100,50)
D5

array([ 80.        ,  80.40816327,  80.81632653,  81.2244898 ,
        81.63265306,  82.04081633,  82.44897959,  82.85714286,
        83.26530612,  83.67346939,  84.08163265,  84.48979592,
        84.89795918,  85.30612245,  85.71428571,  86.12244898,
        86.53061224,  86.93877551,  87.34693878,  87.75510204,
        88.16326531,  88.57142857,  88.97959184,  89.3877551 ,
        89.79591837,  90.20408163,  90.6122449 ,  91.02040816,
        91.42857143,  91.83673469,  92.24489796,  92.65306122,
        93.06122449,  93.46938776,  93.87755102,  94.28571429,
        94.69387755,  95.10204082,  95.51020408,  95.91836735,
        96.32653061,  96.73469388,  97.14285714,  97.55102041,
        97.95918367,  98.36734694,  98.7755102 ,  99.18367347,
        99.59183673, 100.        ])

In [113]:
V1=np.linspace(1,5,50)
V1

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [114]:
V2=np.linspace(5,10,50)
V2

array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

In [115]:
V3=np.linspace(10,15,50)
V3

array([10.        , 10.10204082, 10.20408163, 10.30612245, 10.40816327,
       10.51020408, 10.6122449 , 10.71428571, 10.81632653, 10.91836735,
       11.02040816, 11.12244898, 11.2244898 , 11.32653061, 11.42857143,
       11.53061224, 11.63265306, 11.73469388, 11.83673469, 11.93877551,
       12.04081633, 12.14285714, 12.24489796, 12.34693878, 12.44897959,
       12.55102041, 12.65306122, 12.75510204, 12.85714286, 12.95918367,
       13.06122449, 13.16326531, 13.26530612, 13.36734694, 13.46938776,
       13.57142857, 13.67346939, 13.7755102 , 13.87755102, 13.97959184,
       14.08163265, 14.18367347, 14.28571429, 14.3877551 , 14.48979592,
       14.59183673, 14.69387755, 14.79591837, 14.89795918, 15.        ])

In [116]:
V4=np.linspace(15,20,50)
V4

array([15.        , 15.10204082, 15.20408163, 15.30612245, 15.40816327,
       15.51020408, 15.6122449 , 15.71428571, 15.81632653, 15.91836735,
       16.02040816, 16.12244898, 16.2244898 , 16.32653061, 16.42857143,
       16.53061224, 16.63265306, 16.73469388, 16.83673469, 16.93877551,
       17.04081633, 17.14285714, 17.24489796, 17.34693878, 17.44897959,
       17.55102041, 17.65306122, 17.75510204, 17.85714286, 17.95918367,
       18.06122449, 18.16326531, 18.26530612, 18.36734694, 18.46938776,
       18.57142857, 18.67346939, 18.7755102 , 18.87755102, 18.97959184,
       19.08163265, 19.18367347, 19.28571429, 19.3877551 , 19.48979592,
       19.59183673, 19.69387755, 19.79591837, 19.89795918, 20.        ])

In [117]:
T11=np.linspace(0.25,3,50)
T11

array([0.25      , 0.30612245, 0.3622449 , 0.41836735, 0.4744898 ,
       0.53061224, 0.58673469, 0.64285714, 0.69897959, 0.75510204,
       0.81122449, 0.86734694, 0.92346939, 0.97959184, 1.03571429,
       1.09183673, 1.14795918, 1.20408163, 1.26020408, 1.31632653,
       1.37244898, 1.42857143, 1.48469388, 1.54081633, 1.59693878,
       1.65306122, 1.70918367, 1.76530612, 1.82142857, 1.87755102,
       1.93367347, 1.98979592, 2.04591837, 2.10204082, 2.15816327,
       2.21428571, 2.27040816, 2.32653061, 2.38265306, 2.43877551,
       2.49489796, 2.55102041, 2.60714286, 2.66326531, 2.71938776,
       2.7755102 , 2.83163265, 2.8877551 , 2.94387755, 3.        ])

In [118]:
T21=np.linspace(1.75,4.5,50)
T21

array([1.75      , 1.80612245, 1.8622449 , 1.91836735, 1.9744898 ,
       2.03061224, 2.08673469, 2.14285714, 2.19897959, 2.25510204,
       2.31122449, 2.36734694, 2.42346939, 2.47959184, 2.53571429,
       2.59183673, 2.64795918, 2.70408163, 2.76020408, 2.81632653,
       2.87244898, 2.92857143, 2.98469388, 3.04081633, 3.09693878,
       3.15306122, 3.20918367, 3.26530612, 3.32142857, 3.37755102,
       3.43367347, 3.48979592, 3.54591837, 3.60204082, 3.65816327,
       3.71428571, 3.77040816, 3.82653061, 3.88265306, 3.93877551,
       3.99489796, 4.05102041, 4.10714286, 4.16326531, 4.21938776,
       4.2755102 , 4.33163265, 4.3877551 , 4.44387755, 4.5       ])

In [119]:
T31=np.linspace(0.75,3.5,50)
T31

array([0.75      , 0.80612245, 0.8622449 , 0.91836735, 0.9744898 ,
       1.03061224, 1.08673469, 1.14285714, 1.19897959, 1.25510204,
       1.31122449, 1.36734694, 1.42346939, 1.47959184, 1.53571429,
       1.59183673, 1.64795918, 1.70408163, 1.76020408, 1.81632653,
       1.87244898, 1.92857143, 1.98469388, 2.04081633, 2.09693878,
       2.15306122, 2.20918367, 2.26530612, 2.32142857, 2.37755102,
       2.43367347, 2.48979592, 2.54591837, 2.60204082, 2.65816327,
       2.71428571, 2.77040816, 2.82653061, 2.88265306, 2.93877551,
       2.99489796, 3.05102041, 3.10714286, 3.16326531, 3.21938776,
       3.2755102 , 3.33163265, 3.3877551 , 3.44387755, 3.5       ])

In [120]:
T41=np.linspace(3.25,6,50)
T41

array([3.25      , 3.30612245, 3.3622449 , 3.41836735, 3.4744898 ,
       3.53061224, 3.58673469, 3.64285714, 3.69897959, 3.75510204,
       3.81122449, 3.86734694, 3.92346939, 3.97959184, 4.03571429,
       4.09183673, 4.14795918, 4.20408163, 4.26020408, 4.31632653,
       4.37244898, 4.42857143, 4.48469388, 4.54081633, 4.59693878,
       4.65306122, 4.70918367, 4.76530612, 4.82142857, 4.87755102,
       4.93367347, 4.98979592, 5.04591837, 5.10204082, 5.15816327,
       5.21428571, 5.27040816, 5.32653061, 5.38265306, 5.43877551,
       5.49489796, 5.55102041, 5.60714286, 5.66326531, 5.71938776,
       5.7755102 , 5.83163265, 5.8877551 , 5.94387755, 6.        ])

In [93]:
list(T41)

[np.float64(3.25),
 np.float64(3.306122448979592),
 np.float64(3.3622448979591835),
 np.float64(3.4183673469387754),
 np.float64(3.4744897959183674),
 np.float64(3.5306122448979593),
 np.float64(3.586734693877551),
 np.float64(3.642857142857143),
 np.float64(3.6989795918367347),
 np.float64(3.7551020408163263),
 np.float64(3.811224489795918),
 np.float64(3.86734693877551),
 np.float64(3.923469387755102),
 np.float64(3.979591836734694),
 np.float64(4.035714285714286),
 np.float64(4.091836734693878),
 np.float64(4.1479591836734695),
 np.float64(4.204081632653061),
 np.float64(4.2602040816326525),
 np.float64(4.316326530612245),
 np.float64(4.372448979591836),
 np.float64(4.428571428571429),
 np.float64(4.48469387755102),
 np.float64(4.540816326530612),
 np.float64(4.596938775510204),
 np.float64(4.653061224489796),
 np.float64(4.709183673469388),
 np.float64(4.76530612244898),
 np.float64(4.821428571428571),
 np.float64(4.877551020408164),
 np.float64(4.933673469387755),
 np.float64(4.98

In [121]:
T12=np.linspace(3,6,50)
T12

array([3.        , 3.06122449, 3.12244898, 3.18367347, 3.24489796,
       3.30612245, 3.36734694, 3.42857143, 3.48979592, 3.55102041,
       3.6122449 , 3.67346939, 3.73469388, 3.79591837, 3.85714286,
       3.91836735, 3.97959184, 4.04081633, 4.10204082, 4.16326531,
       4.2244898 , 4.28571429, 4.34693878, 4.40816327, 4.46938776,
       4.53061224, 4.59183673, 4.65306122, 4.71428571, 4.7755102 ,
       4.83673469, 4.89795918, 4.95918367, 5.02040816, 5.08163265,
       5.14285714, 5.20408163, 5.26530612, 5.32653061, 5.3877551 ,
       5.44897959, 5.51020408, 5.57142857, 5.63265306, 5.69387755,
       5.75510204, 5.81632653, 5.87755102, 5.93877551, 6.        ])

In [122]:
T22=np.linspace(4.5,7.5,50)
T22

array([4.5       , 4.56122449, 4.62244898, 4.68367347, 4.74489796,
       4.80612245, 4.86734694, 4.92857143, 4.98979592, 5.05102041,
       5.1122449 , 5.17346939, 5.23469388, 5.29591837, 5.35714286,
       5.41836735, 5.47959184, 5.54081633, 5.60204082, 5.66326531,
       5.7244898 , 5.78571429, 5.84693878, 5.90816327, 5.96938776,
       6.03061224, 6.09183673, 6.15306122, 6.21428571, 6.2755102 ,
       6.33673469, 6.39795918, 6.45918367, 6.52040816, 6.58163265,
       6.64285714, 6.70408163, 6.76530612, 6.82653061, 6.8877551 ,
       6.94897959, 7.01020408, 7.07142857, 7.13265306, 7.19387755,
       7.25510204, 7.31632653, 7.37755102, 7.43877551, 7.5       ])

In [123]:
T32=np.linspace(3.5,6.5,50)
T32

array([3.5       , 3.56122449, 3.62244898, 3.68367347, 3.74489796,
       3.80612245, 3.86734694, 3.92857143, 3.98979592, 4.05102041,
       4.1122449 , 4.17346939, 4.23469388, 4.29591837, 4.35714286,
       4.41836735, 4.47959184, 4.54081633, 4.60204082, 4.66326531,
       4.7244898 , 4.78571429, 4.84693878, 4.90816327, 4.96938776,
       5.03061224, 5.09183673, 5.15306122, 5.21428571, 5.2755102 ,
       5.33673469, 5.39795918, 5.45918367, 5.52040816, 5.58163265,
       5.64285714, 5.70408163, 5.76530612, 5.82653061, 5.8877551 ,
       5.94897959, 6.01020408, 6.07142857, 6.13265306, 6.19387755,
       6.25510204, 6.31632653, 6.37755102, 6.43877551, 6.5       ])

In [124]:
T42=np.linspace(6,9,50)
T42

array([6.        , 6.06122449, 6.12244898, 6.18367347, 6.24489796,
       6.30612245, 6.36734694, 6.42857143, 6.48979592, 6.55102041,
       6.6122449 , 6.67346939, 6.73469388, 6.79591837, 6.85714286,
       6.91836735, 6.97959184, 7.04081633, 7.10204082, 7.16326531,
       7.2244898 , 7.28571429, 7.34693878, 7.40816327, 7.46938776,
       7.53061224, 7.59183673, 7.65306122, 7.71428571, 7.7755102 ,
       7.83673469, 7.89795918, 7.95918367, 8.02040816, 8.08163265,
       8.14285714, 8.20408163, 8.26530612, 8.32653061, 8.3877551 ,
       8.44897959, 8.51020408, 8.57142857, 8.63265306, 8.69387755,
       8.75510204, 8.81632653, 8.87755102, 8.93877551, 9.        ])

In [125]:
T13=np.linspace(6,8,50)
T13

array([6.        , 6.04081633, 6.08163265, 6.12244898, 6.16326531,
       6.20408163, 6.24489796, 6.28571429, 6.32653061, 6.36734694,
       6.40816327, 6.44897959, 6.48979592, 6.53061224, 6.57142857,
       6.6122449 , 6.65306122, 6.69387755, 6.73469388, 6.7755102 ,
       6.81632653, 6.85714286, 6.89795918, 6.93877551, 6.97959184,
       7.02040816, 7.06122449, 7.10204082, 7.14285714, 7.18367347,
       7.2244898 , 7.26530612, 7.30612245, 7.34693878, 7.3877551 ,
       7.42857143, 7.46938776, 7.51020408, 7.55102041, 7.59183673,
       7.63265306, 7.67346939, 7.71428571, 7.75510204, 7.79591837,
       7.83673469, 7.87755102, 7.91836735, 7.95918367, 8.        ])

In [126]:
T23=np.linspace(7.5,9.5,50)
T23

array([7.5       , 7.54081633, 7.58163265, 7.62244898, 7.66326531,
       7.70408163, 7.74489796, 7.78571429, 7.82653061, 7.86734694,
       7.90816327, 7.94897959, 7.98979592, 8.03061224, 8.07142857,
       8.1122449 , 8.15306122, 8.19387755, 8.23469388, 8.2755102 ,
       8.31632653, 8.35714286, 8.39795918, 8.43877551, 8.47959184,
       8.52040816, 8.56122449, 8.60204082, 8.64285714, 8.68367347,
       8.7244898 , 8.76530612, 8.80612245, 8.84693878, 8.8877551 ,
       8.92857143, 8.96938776, 9.01020408, 9.05102041, 9.09183673,
       9.13265306, 9.17346939, 9.21428571, 9.25510204, 9.29591837,
       9.33673469, 9.37755102, 9.41836735, 9.45918367, 9.5       ])

In [127]:
T33=np.linspace(6.5,8.5,50)
T33

array([6.5       , 6.54081633, 6.58163265, 6.62244898, 6.66326531,
       6.70408163, 6.74489796, 6.78571429, 6.82653061, 6.86734694,
       6.90816327, 6.94897959, 6.98979592, 7.03061224, 7.07142857,
       7.1122449 , 7.15306122, 7.19387755, 7.23469388, 7.2755102 ,
       7.31632653, 7.35714286, 7.39795918, 7.43877551, 7.47959184,
       7.52040816, 7.56122449, 7.60204082, 7.64285714, 7.68367347,
       7.7244898 , 7.76530612, 7.80612245, 7.84693878, 7.8877551 ,
       7.92857143, 7.96938776, 8.01020408, 8.05102041, 8.09183673,
       8.13265306, 8.17346939, 8.21428571, 8.25510204, 8.29591837,
       8.33673469, 8.37755102, 8.41836735, 8.45918367, 8.5       ])

In [128]:
T43=np.linspace(9,11,50)
T43

array([ 9.        ,  9.04081633,  9.08163265,  9.12244898,  9.16326531,
        9.20408163,  9.24489796,  9.28571429,  9.32653061,  9.36734694,
        9.40816327,  9.44897959,  9.48979592,  9.53061224,  9.57142857,
        9.6122449 ,  9.65306122,  9.69387755,  9.73469388,  9.7755102 ,
        9.81632653,  9.85714286,  9.89795918,  9.93877551,  9.97959184,
       10.02040816, 10.06122449, 10.10204082, 10.14285714, 10.18367347,
       10.2244898 , 10.26530612, 10.30612245, 10.34693878, 10.3877551 ,
       10.42857143, 10.46938776, 10.51020408, 10.55102041, 10.59183673,
       10.63265306, 10.67346939, 10.71428571, 10.75510204, 10.79591837,
       10.83673469, 10.87755102, 10.91836735, 10.95918367, 11.        ])

In [129]:
T14=np.linspace(8,12,50)
T14

array([ 8.        ,  8.08163265,  8.16326531,  8.24489796,  8.32653061,
        8.40816327,  8.48979592,  8.57142857,  8.65306122,  8.73469388,
        8.81632653,  8.89795918,  8.97959184,  9.06122449,  9.14285714,
        9.2244898 ,  9.30612245,  9.3877551 ,  9.46938776,  9.55102041,
        9.63265306,  9.71428571,  9.79591837,  9.87755102,  9.95918367,
       10.04081633, 10.12244898, 10.20408163, 10.28571429, 10.36734694,
       10.44897959, 10.53061224, 10.6122449 , 10.69387755, 10.7755102 ,
       10.85714286, 10.93877551, 11.02040816, 11.10204082, 11.18367347,
       11.26530612, 11.34693878, 11.42857143, 11.51020408, 11.59183673,
       11.67346939, 11.75510204, 11.83673469, 11.91836735, 12.        ])

In [130]:
T24=np.linspace(9.5,13.5,50)
T24

array([ 9.5       ,  9.58163265,  9.66326531,  9.74489796,  9.82653061,
        9.90816327,  9.98979592, 10.07142857, 10.15306122, 10.23469388,
       10.31632653, 10.39795918, 10.47959184, 10.56122449, 10.64285714,
       10.7244898 , 10.80612245, 10.8877551 , 10.96938776, 11.05102041,
       11.13265306, 11.21428571, 11.29591837, 11.37755102, 11.45918367,
       11.54081633, 11.62244898, 11.70408163, 11.78571429, 11.86734694,
       11.94897959, 12.03061224, 12.1122449 , 12.19387755, 12.2755102 ,
       12.35714286, 12.43877551, 12.52040816, 12.60204082, 12.68367347,
       12.76530612, 12.84693878, 12.92857143, 13.01020408, 13.09183673,
       13.17346939, 13.25510204, 13.33673469, 13.41836735, 13.5       ])

In [131]:
T34=np.linspace(8.5,12.5,50)
T34

array([ 8.5       ,  8.58163265,  8.66326531,  8.74489796,  8.82653061,
        8.90816327,  8.98979592,  9.07142857,  9.15306122,  9.23469388,
        9.31632653,  9.39795918,  9.47959184,  9.56122449,  9.64285714,
        9.7244898 ,  9.80612245,  9.8877551 ,  9.96938776, 10.05102041,
       10.13265306, 10.21428571, 10.29591837, 10.37755102, 10.45918367,
       10.54081633, 10.62244898, 10.70408163, 10.78571429, 10.86734694,
       10.94897959, 11.03061224, 11.1122449 , 11.19387755, 11.2755102 ,
       11.35714286, 11.43877551, 11.52040816, 11.60204082, 11.68367347,
       11.76530612, 11.84693878, 11.92857143, 12.01020408, 12.09183673,
       12.17346939, 12.25510204, 12.33673469, 12.41836735, 12.5       ])

In [132]:
T44=np.linspace(11,15,50)
T44

array([11.        , 11.08163265, 11.16326531, 11.24489796, 11.32653061,
       11.40816327, 11.48979592, 11.57142857, 11.65306122, 11.73469388,
       11.81632653, 11.89795918, 11.97959184, 12.06122449, 12.14285714,
       12.2244898 , 12.30612245, 12.3877551 , 12.46938776, 12.55102041,
       12.63265306, 12.71428571, 12.79591837, 12.87755102, 12.95918367,
       13.04081633, 13.12244898, 13.20408163, 13.28571429, 13.36734694,
       13.44897959, 13.53061224, 13.6122449 , 13.69387755, 13.7755102 ,
       13.85714286, 13.93877551, 14.02040816, 14.10204082, 14.18367347,
       14.26530612, 14.34693878, 14.42857143, 14.51020408, 14.59183673,
       14.67346939, 14.75510204, 14.83673469, 14.91836735, 15.        ])

In [133]:
T15=np.linspace(12,20,50)
T15

array([12.        , 12.16326531, 12.32653061, 12.48979592, 12.65306122,
       12.81632653, 12.97959184, 13.14285714, 13.30612245, 13.46938776,
       13.63265306, 13.79591837, 13.95918367, 14.12244898, 14.28571429,
       14.44897959, 14.6122449 , 14.7755102 , 14.93877551, 15.10204082,
       15.26530612, 15.42857143, 15.59183673, 15.75510204, 15.91836735,
       16.08163265, 16.24489796, 16.40816327, 16.57142857, 16.73469388,
       16.89795918, 17.06122449, 17.2244898 , 17.3877551 , 17.55102041,
       17.71428571, 17.87755102, 18.04081633, 18.20408163, 18.36734694,
       18.53061224, 18.69387755, 18.85714286, 19.02040816, 19.18367347,
       19.34693878, 19.51020408, 19.67346939, 19.83673469, 20.        ])

In [134]:
T25=np.linspace(13.5,21.5,50)
T25

array([13.5       , 13.66326531, 13.82653061, 13.98979592, 14.15306122,
       14.31632653, 14.47959184, 14.64285714, 14.80612245, 14.96938776,
       15.13265306, 15.29591837, 15.45918367, 15.62244898, 15.78571429,
       15.94897959, 16.1122449 , 16.2755102 , 16.43877551, 16.60204082,
       16.76530612, 16.92857143, 17.09183673, 17.25510204, 17.41836735,
       17.58163265, 17.74489796, 17.90816327, 18.07142857, 18.23469388,
       18.39795918, 18.56122449, 18.7244898 , 18.8877551 , 19.05102041,
       19.21428571, 19.37755102, 19.54081633, 19.70408163, 19.86734694,
       20.03061224, 20.19387755, 20.35714286, 20.52040816, 20.68367347,
       20.84693878, 21.01020408, 21.17346939, 21.33673469, 21.5       ])

In [135]:
T35=np.linspace(12.5,20.5,50)
T35

array([12.5       , 12.66326531, 12.82653061, 12.98979592, 13.15306122,
       13.31632653, 13.47959184, 13.64285714, 13.80612245, 13.96938776,
       14.13265306, 14.29591837, 14.45918367, 14.62244898, 14.78571429,
       14.94897959, 15.1122449 , 15.2755102 , 15.43877551, 15.60204082,
       15.76530612, 15.92857143, 16.09183673, 16.25510204, 16.41836735,
       16.58163265, 16.74489796, 16.90816327, 17.07142857, 17.23469388,
       17.39795918, 17.56122449, 17.7244898 , 17.8877551 , 18.05102041,
       18.21428571, 18.37755102, 18.54081633, 18.70408163, 18.86734694,
       19.03061224, 19.19387755, 19.35714286, 19.52040816, 19.68367347,
       19.84693878, 20.01020408, 20.17346939, 20.33673469, 20.5       ])

In [136]:
T45=np.linspace(15,23,50)
T45

array([15.        , 15.16326531, 15.32653061, 15.48979592, 15.65306122,
       15.81632653, 15.97959184, 16.14285714, 16.30612245, 16.46938776,
       16.63265306, 16.79591837, 16.95918367, 17.12244898, 17.28571429,
       17.44897959, 17.6122449 , 17.7755102 , 17.93877551, 18.10204082,
       18.26530612, 18.42857143, 18.59183673, 18.75510204, 18.91836735,
       19.08163265, 19.24489796, 19.40816327, 19.57142857, 19.73469388,
       19.89795918, 20.06122449, 20.2244898 , 20.3877551 , 20.55102041,
       20.71428571, 20.87755102, 21.04081633, 21.20408163, 21.36734694,
       21.53061224, 21.69387755, 21.85714286, 22.02040816, 22.18367347,
       22.34693878, 22.51020408, 22.67346939, 22.83673469, 23.        ])

In [95]:
l0=[]
for i in T45:
    l0.append(float(i))
l0

[15.0,
 15.16326530612245,
 15.326530612244898,
 15.489795918367347,
 15.653061224489797,
 15.816326530612244,
 15.979591836734693,
 16.142857142857142,
 16.306122448979593,
 16.46938775510204,
 16.632653061224488,
 16.79591836734694,
 16.959183673469386,
 17.122448979591837,
 17.285714285714285,
 17.448979591836736,
 17.612244897959183,
 17.775510204081634,
 17.93877551020408,
 18.10204081632653,
 18.26530612244898,
 18.428571428571427,
 18.591836734693878,
 18.755102040816325,
 18.918367346938776,
 19.081632653061224,
 19.244897959183675,
 19.408163265306122,
 19.57142857142857,
 19.73469387755102,
 19.897959183673468,
 20.06122448979592,
 20.224489795918366,
 20.387755102040817,
 20.551020408163264,
 20.714285714285715,
 20.877551020408163,
 21.04081632653061,
 21.20408163265306,
 21.36734693877551,
 21.53061224489796,
 21.693877551020407,
 21.857142857142858,
 22.020408163265305,
 22.183673469387756,
 22.346938775510203,
 22.51020408163265,
 22.6734693877551,
 22.836734693877553,
 

In [447]:
H={
    'H1':H1.reshape(-1,1),
    'H2':H2.reshape(-1,1),
    'H3':H3.reshape(-1,1),
    'H4':H4.reshape(-1,1),
    'H5':H5.reshape(-1,1),   
}

V={
    'V1':V1.reshape(-1,1),
    'V2':V2.reshape(-1,1),
    'V3':V3.reshape(-1,1),
    'V4':V4.reshape(-1,1), 
}

D={
    'D1':D1.reshape(-1,1),
    'D2':D2.reshape(-1,1),
    'D3':D3.reshape(-1,1),
    'D4':D4.reshape(-1,1),
    'D5':D5.reshape(-1,1),
}

In [194]:
V['V1']

array([[1.        ],
       [1.08163265],
       [1.16326531],
       [1.24489796],
       [1.32653061],
       [1.40816327],
       [1.48979592],
       [1.57142857],
       [1.65306122],
       [1.73469388],
       [1.81632653],
       [1.89795918],
       [1.97959184],
       [2.06122449],
       [2.14285714],
       [2.2244898 ],
       [2.30612245],
       [2.3877551 ],
       [2.46938776],
       [2.55102041],
       [2.63265306],
       [2.71428571],
       [2.79591837],
       [2.87755102],
       [2.95918367],
       [3.04081633],
       [3.12244898],
       [3.20408163],
       [3.28571429],
       [3.36734694],
       [3.44897959],
       [3.53061224],
       [3.6122449 ],
       [3.69387755],
       [3.7755102 ],
       [3.85714286],
       [3.93877551],
       [4.02040816],
       [4.10204082],
       [4.18367347],
       [4.26530612],
       [4.34693878],
       [4.42857143],
       [4.51020408],
       [4.59183673],
       [4.67346939],
       [4.75510204],
       [4.836

In [195]:
l=[]
for i in 

SyntaxError: invalid syntax (2786021089.py, line 2)

In [196]:
len(H)

5

In [492]:
def create_H_V_D_T(V,H,D):
    len_V=len(V)
    len_H=len(H)
    len_D=len(D)
    HVD={}

    for i in range(len_H):
        for j in range(len_V):
            for k in range(len_D):
                HVD['H'+str(i+1)+'_V'+str(j+1)+'_D'+str(k+1)]=[H['H'+str(i+1)],V['V'+str(j+1)],D['D'+str(k+1)]]

    HVDT={}
    L_VH=['H1','H2','H3','H4','H5']
    DeltaTime=[[0,0],[1.5,2],[0,0.5],[2,3],[0,0]]
    
    for j in range(len(L_VH)):
        for i in HVD:
            if i[:2]==L_VH[j]:
                
                D_HVD= [HVD[i][2][0],HVD[i][2][-1]]
                D_HVD
                V_HVD= [HVD[i][1][0],HVD[i][1][-1]]
                V_HVD
                T_HVD= [(D_HVD[0]/V_HVD[0])+DeltaTime[j][0],(D_HVD[1]/V_HVD[1])+DeltaTime[j][1]]
                T_HVD
                T=np.linspace(T_HVD[0],T_HVD[1],50)
                
                HVD[i].append(T)
                HVDT[i+'_T']= HVD[i]

                
    return HVDT

In [501]:
def create_pandas_dataset(V,H,D):

    import pandas as pd
    HVDT= create_H_V_D_T(V,H,D)
    
    df= pd.DataFrame({
        'Heure_Depart':[],
        'Vitesse_Moyenne':[],
        'Distance':[],
        'Temps_Estimé':[]
    })
    
    for i in HVDT:
        
        H=[]
        V=[]
        D=[]
        T=[]

        for j in HVDT[i][0]:
            H.append(float(j))
        for j in HVDT[i][1]:
            V.append(float(j))
        for j in HVDT[i][2]:
            D.append(float(j))
        for j in HVDT[i][3]:
            T.append(float(j))
            
        datasets = pd.DataFrame({'Heure_Depart':H})
        datasets['Vitesse_Moyenne'] = pd.DataFrame({'Vitesse_Moyenne':V})
        datasets['Distance'] = pd.DataFrame({'Distance':D})
        datasets['Temps_Estimé'] = pd.DataFrame({'Temps_Estimé':T})

        df= pd.concat([df, datasets], ignore_index=True)

    df.to_csv('Transport_Set.csv', index=False)

    return df

In [502]:
df=create_pandas_dataset(V,H,D)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_2532\800369299.py:21: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  H.append(float(j))
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_2532\800369299.py:23: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  V.append(float(j))
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_2532\800369299.py:25: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  D.append(float(j))
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_2532\800369299.py:27: Deprec

In [503]:
df

,Heure_Depart,Vitesse_Moyenne,Distance,Temps_Estimé
0,4.500000,1.000000,10.000000,10.000000
1,4.551020,1.081633,10.204082,9.877551
2,4.602041,1.163265,10.408163,9.755102
3,4.653061,1.244898,10.612245,9.632653
4,4.704082,1.326531,10.816327,9.510204
...,...,...,...,...
4995,22.030612,19.591837,98.367347,5.027211
4996,22.097959,19.693878,98.775510,5.020408
4997,22.165306,19.795918,99.183673,5.013605
4998,22.232653,19.897959,99.591837,5.006803


In [493]:
HVDT=create_H_V_D_T(V,H,D)

In [491]:
HVDT

{'H1_V1_D1_T': [array([[4.5       ],
         [4.55102041],
         [4.60204082],
         [4.65306122],
         [4.70408163],
         [4.75510204],
         [4.80612245],
         [4.85714286],
         [4.90816327],
         [4.95918367],
         [5.01020408],
         [5.06122449],
         [5.1122449 ],
         [5.16326531],
         [5.21428571],
         [5.26530612],
         [5.31632653],
         [5.36734694],
         [5.41836735],
         [5.46938776],
         [5.52040816],
         [5.57142857],
         [5.62244898],
         [5.67346939],
         [5.7244898 ],
         [5.7755102 ],
         [5.82653061],
         [5.87755102],
         [5.92857143],
         [5.97959184],
         [6.03061224],
         [6.08163265],
         [6.13265306],
         [6.18367347],
         [6.23469388],
         [6.28571429],
         [6.33673469],
         [6.3877551 ],
         [6.43877551],
         [6.48979592],
         [6.54081633],
         [6.59183673],
         [6.64285714

In [515]:
df= pd.read_csv('Transport_Set.csv')
X=df[['Heure_Depart','Vitesse_Moyenne','Distance']]
X

,Heure_Depart,Vitesse_Moyenne,Distance
0,4.500000,1.000000,10.000000
1,4.551020,1.081633,10.204082
2,4.602041,1.163265,10.408163
3,4.653061,1.244898,10.612245
4,4.704082,1.326531,10.816327
...,...,...,...
4995,22.030612,19.591837,98.367347
4996,22.097959,19.693878,98.775510
4997,22.165306,19.795918,99.183673
4998,22.232653,19.897959,99.591837


In [545]:
def transport_LinearRegression_modal(df_file):
    import pandas as pd
    from sklearn.model_selection import train_test_split
    from sklearn.linear_model import LinearRegression

    df= pd.read_csv(df_file)
    X=df[['Heure_Depart','Vitesse_Moyenne','Distance']].values
    y=df[['Temps_Estimé']].values


    X_train, X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=40)
    
    modal= LinearRegression()
    modal.fit(X_train,y_train)

    prediction_train=modal.predict(X_train)
    prediction_test=modal.predict(X_test)
    
    score_train=modal.score(X_train,y_train)
    score_test=modal.score(X_test,y_test)
    
    print("Score de l'entrainement : ", score_train)
    print("Score du test : ", score_test)

    dict_train={
        'X':X_train,
        'y':y_train,
        'prediction':prediction_train,
        'score':score_train
    }
    
    dict_test={
        'X':X_test,
        'y':y_test,
        'prediction':prediction_test,
        'score':score_test
    }

    
    return(modal,dict_train,dict_test)

In [550]:
modal_LinearRegression,dict_train_LinearRegression,dict_test_LinearRegression=transport_LinearRegression_modal('Transport_Set.csv')

Score de l'entrainement :  0.5528174740882905
Score du test :  0.5225748852932044


In [547]:
def transport_RandomForestRegressor_modal(df_file):
    import pandas as pd
    from sklearn.model_selection import train_test_split
    from sklearn.ensemble import RandomForestRegressor

    df= pd.read_csv(df_file)
    X=df[['Heure_Depart','Vitesse_Moyenne','Distance']].values
    y=df[['Temps_Estimé']].values


    X_train, X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=40)
    
    modal= RandomForestRegressor(n_estimators=100, random_state=42)
    modal.fit(X_train,y_train)

    prediction_train=modal.predict(X_train)
    prediction_test=modal.predict(X_test)
    
    score_train=modal.score(X_train,y_train)
    score_test=modal.score(X_test,y_test)
    
    print("Score de l'entrainement : ", score_train)
    print("Score du test : ", score_test)

    dict_train={
        'X':X_train,
        'y':y_train,
        'prediction':prediction_train,
        'score':score_train
    }
    
    dict_test={
        'X':X_test,
        'y':y_test,
        'prediction':prediction_test,
        'score':score_test
    }

    
    return(modal,dict_train,dict_test)

In [549]:
modal_RandomForestRegressor,dict_train_RandomForestRegressor,dict_test_RandomForestRegressor=transport_RandomForestRegressor_modal('Transport_Set.csv')

C:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Score de l'entrainement :  0.9997401628792602
Score du test :  0.9985785197056156


In [552]:
modal_LinearRegression.predict([[16.5,17.9,8]])

array([[-9.9402413]])

In [553]:
modal_RandomForestRegressor.predict([[16.5,17.9,8]])

array([2.62503401])